In [2]:
import cv2
cv2.__version__

'5.0.0'

**Task:** Load an image and print its shape, dtype, and the pixel value at (50, 50).

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# Loading an image
img = cv2.imread('sampleimg.png')
print("image pixels",img)
print("Loaded image shape:(height,width,channel)", img.shape)
print("Loaded image dtype:", img.dtype)
print("The pixel value at (50,50) is:", img[50,50])

image pixels [[[24 24 24]
  [24 24 24]
  [24 24 24]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 [[24 24 24]
  [24 24 24]
  [24 24 24]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 [[24 24 24]
  [24 24 24]
  [24 24 24]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 ...

 [[31 31 31]
  [31 31 31]
  [31 31 31]
  ...
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[31 31 31]
  [31 31 31]
  [31 31 31]
  ...
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[31 31 31]
  [31 31 31]
  [31 31 31]
  ...
  [31 31 31]
  [31 31 31]
  [31 31 31]]]
Loaded image shape:(height,width,channel) (517, 758, 3)
Loaded image dtype: uint8
The pixel value at (50,50) is: [31 31 31]


In [5]:
cv2.imwrite('output.png', img)

True

In [8]:
cv2.imshow("Output",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.imshow('image_rgb',img_rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
apple = cv2.imread('apple.png')
apple

array([[[ 42,  36,  34],
        [ 42,  36,  34],
        [ 42,  36,  34],
        ...,
        [ 42,  36,  34],
        [ 42,  36,  34],
        [ 42,  36,  34]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [19]:
cv2.imshow("apple",apple)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
converted_img = cv2.cvtColor(apple, cv2.COLOR_BGR2RGB)
cv2.imshow("Live", converted_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
import cv2

cap = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter("out.avi",fourcc,20.0,(640,480))
while True:
    ret,frame = cap.read()
    if not ret:
        break
    cv2.imshow("Video",frame)
    out.write(frame)
    
    if cv2.waitKey(1)== ord('q'):
        break
    
cap.release()
out.release()
cv2.destroyAllWindows()
    

In [8]:
import cv2 
import numpy as np

img = np.zeros((480,220,3),np.uint8)
# cv2.line(img,(0,0),(220,480),(0,255,255),2)
cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
cv2.arrowedLine(img,(480,100),(0,220),(0,255,250),5)
cv2.imshow("Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
import cv2 
import numpy as np

img = np.zeros((500,500,3),np.uint8)
cv2.imshow('img',img)
cv2.line(img,(0,0),(100,320),(255,0,0),3)
cv2.rectangle(img,(120,120),(200,200),(0,255,0),3)
cv2.circle(img,(220,220),50,(0,0,255),3)
pts = np.array([[300,200],[300,400],[500,200],[500,400]])
cv2.polylines(img,[pts],True,(255,255,255),3)
cv2.putText(img,'Hello',(0,500),cv2.FONT_HERSHEY_SIMPLEX,2,(0,255,255),3)

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()