In [ ]:
# # Background removal for live video 
# # type:ignore
import cv2

cap = cv2.VideoCapture(0)

while True:
    ret,frame = cap.read()
    
    grayed = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    # Removing the noise 
    blur = cv2.medianBlur(grayed,5)
    # Applying the thresholding
    _,thresh = cv2.threshold(blur,110,255,cv2.THRESH_BINARY_INV)
    
    # erode
    mask = cv2.erode(thresh,None,2)
    # removed background
    back_rem = cv2.bitwise_and(frame,frame,mask=mask)
    cv2.imshow("live",frame)
    cv2.imshow("Back_removed",back_rem)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

# `Image thresholding techniques`
1. **Simple Thresholding**
    - This is the simplest form of thresholding, where each pixel in the image is compared with a fixed threshold value. If the pixel value is greater than the threshold, it is set to a maximum value. Otherwise, it is set to zero
    - It is not very useful because it is very sensitive to the threshold value.
2. **Adaptive Thresholding**
    - The threshold value is not fixed, but instead is calculated for each pixel based on the mean or Gaussian-weighted mean of its surrounding pixels.
    - It is very useful because it is less sensitive to the threshold value.
3. **Otsu's Thresholding**
    - This is a technique for **automatically calculating the threshold value based on the image histogram**. It assumes that there are two classes of pixels in the image - foreground and background - and **finds the threshold that maximizes the variance between these two classes**.

4. **Binary thresholding**
    - This is similar to simple thresholding, but instead of setting the pixels above the threshold to a maximum value, they are set to a specific value (usually 1) to create a binary image. This can be done using the cv2.threshold() function with the cv2.THRESH_BINARY flag

In [ ]:
# thresholding
import cv2

img = cv2.imread("parrot.jpg",0)
cv2.imshow("Original", img)
# 1. Simple thresholding
threshold_val = 100
max_val = 255

ret,thresh = cv2.threshold(
    img, # input image
    threshold_val, # threshold value
    max_val, # max value
    cv2.THRESH_BINARY # threshold type
)
cv2.imshow("Simple thresholding", thresh)

# 2. Adaptive thresholding: best threshold for a range of values
adaptive_thresh = cv2.adaptiveThreshold(
    img, # input image
    max_val, # max value
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C, # threshold type/method
    cv2.THRESH_BINARY_INV, # threshold type
    11, # block size
    2 # C value
)
cv2.imshow("Adaptive thresholding", adaptive_thresh)

# 3. Otsu's thresholding
ret,otsu_thresh = cv2.threshold(
    img, # input image
    0, # threshold value
    max_val, # max value
    cv2.THRESH_BINARY + cv2.THRESH_OTSU # threshold type
)
cv2.imshow("Otsu's thresholding", otsu_thresh)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# thresholding
import cv2


cap = cv2.VideoCapture(0)
while True:
    ret,frame = cap.read()
    if not ret: break
    cv2.imshow("Original", frame)
    # 1. Simple thresholding
    threshold_val = 100
    max_val = 255
    grayed = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    ret,thresh = cv2.threshold(
        grayed, # input image
        threshold_val, # threshold value
        max_val, # max value
        cv2.THRESH_BINARY # threshold type
    )
    cv2.imshow("Simple thresholding", thresh)

    # # 2. Adaptive thresholding: best threshold for a range of values
    adaptive_thresh = cv2.adaptiveThreshold(
        grayed, # input image
        max_val, # max value
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C, # threshold type/method
        cv2.THRESH_BINARY_INV, # threshold type can use cv2.THRESH_BINARY or cv2.THRESH_BINARY_INV
        11, # block size
        2 # C value
    )
    cv2.imshow("Adaptive thresholding", adaptive_thresh)

    # 3. Otsu's thresholding
    ret,otsu_thresh = cv2.threshold(
        grayed, # input image
        100, # threshold value
        max_val, # max value
        cv2.THRESH_BINARY + cv2.THRESH_OTSU # threshold type
    )
    cv2.imshow("Otsu's thresholding", otsu_thresh)
    if cv2.waitKey(1)==ord('q'): break
cap.release()
cv2.destroyAllWindows()

In [124]:
# NOTE just run this if your cell's output is not closing up it will save up your kernel from crashing

cap.release()
cv2.destroyAllWindows()

# `Finding and Drawing Contours`

Countours are the outlines of objects in an image. They are useful for many tasks, such as object detection, tracking, and shape analysis.


In [111]:
import cv2
import numpy as np

# Load the image 
img = cv2.resize(cv2.imread('desk.jpeg',0),(480,720))

# Apply thresholding to that image
ret,thresh = cv2.threshold(
    img,
    100,  ## threshold value
    255,  ## max value
    cv2.THRESH_BINARY  ## threshold type
)

# FIND CONTOURS
contours, hierarchy = cv2.findContours(
    thresh,
    cv2.RETR_TREE,  ## retrieve contours
    cv2.CHAIN_APPROX_SIMPLE  ## approximation method
)

# DRAW CONTOURS
cv2.drawContours(img, contours, -1, (255, 255, 255), 2)
cv2.imshow("Original Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
import cv2

cap = cv2.VideoCapture(0)

while True:
    ret,frame = cap.read()
    if not ret: break
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    ret, thresh = cv2.threshold(
        gray,
        127,
        255,
        cv2.THRESH_BINARY
    )
    contours, hierarchy = cv2.findContours(
        thresh,
        cv2.RETR_TREE,  ## retrieve contours
        cv2.CHAIN_APPROX_SIMPLE  ## approximation method
    )
    cv2.drawContours(frame, contours, -1, (0, 255, 0), 2)
    
    cv2.imshow("Original",frame)
    cv2.imshow("Live",thresh)
    if cv2.waitKey(1) & 0xFF == ord('q'): break

cap.release()
cv2.destroyAllWindows()

# `Detect Simple Geometric Shapes`
Steps:
1. Load the image
2. Convert the image to grayscale
3. Apply a blur to remove noise
4. Apply a threshold to create a binary image
5. Find contours in the binary image
6. Draw the contours on the original image

In [112]:
import cv2

img = np.zeros((480,480,3),np.uint8)
cv2.rectangle(
    img,
    (100,100),
    (300,300),
    (0,0,255),
    3
)
cv2.circle(
    img,
    (300,350),
    20,
    (255,0,0),
    3
)
# APPLY canny edge detection
canny = cv2.Canny(img,50,150,apertureSize=3)
cv2.imshow("Canny Edge Detection",canny)
# Find Contours in the edge image
contours,hirearchy = cv2.findContours(
    canny,
    cv2.RETR_TREE,
    cv2.CHAIN_APPROX_SIMPLE
)

# loop through the contour and check if it matches a circle,square, or traingle
for cnt in contours:
    # Calculate the perimeter of each cnt
    perimeter = cv2.arcLength(cnt,True)
    # approzimate the shape of the contour
    approx = cv2.approxPolyDP(cnt,0.04*perimeter,True)
    # Calculate number of vertices of the approzimated shape
    num_vertices = len(approx)
    
    if num_vertices == 3:
        cv2.drawContours(
            img,[approx],0,(0,255,255),2
        )
        cv2.putText(
            img,
            "Triangle",
            tuple(approx[0][0]),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,
            (255,255,255),
            2
        )
    elif num_vertices == 4:
        # Could be rectangle or square 
        x,y,w,h = cv2.boundingRect(cnt)
        aspect_ratio = float(w)/h
        if 0.95<=aspect_ratio<=1.05:
            cv2.drawContours(
                img,[approx],0,(0,0,255),2
            )
            cv2.putText(
                img,
                "Square",
                tuple(approx[0][0]),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,(0,0,255),2
            )
        else:
            cv2.drawContours(img,[approx],0,(0,255,255),2)
            cv2.putText(
                img,
                "Rectangle",
                tuple(approx[0][0]),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,(255,255,0),2
            )
    else:
        cv2.drawContours(img,[approx],0,(255,0,0),2)
        cv2.putText(
            img,
            "Circle",
            tuple(approx[0][0]),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,(255,0,0),2
        )



cv2.imshow("Original Image",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [113]:
import cv2
import numpy as np

img = np.zeros((480,480,3),np.uint8)
cv2.rectangle(
    img,
    (100,100),
    (300,300),
    (0,0,255),
    3
)
cv2.circle(
    img,
    (300,350),
    20,
    (255,0,0),
    3
)

# Converting to grayscale
grayed = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# converting it to binary
ret,thresh = cv2.threshold(
    img,
    125,
    255,
    cv2.THRESH_BINARY_INV
)
# DETECTING EDGES
edges = cv2.Canny(
    img,
    100,
    200
)

cv2.imshow("canny",edges)

# Finding the contours
contours,hirearchy = cv2.findContours(
    edges,
    cv2.RETR_LIST,
    cv2.CHAIN_APPROX_SIMPLE
)
print(contours)
print(hirearchy)

# draw the contours
count_img = cv2.drawContours(
    edges,
    contours,
    -1,
    (255,255,255),
    3
    
)

cv2.imshow("image",count_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(array([[[296, 333]],

       [[297, 332]],

       [[303, 332]],

       [[304, 333]],

       [[306, 333]],

       [[307, 334]],

       [[308, 334]],

       [[310, 336]],

       [[311, 336]],

       [[314, 339]],

       [[314, 340]],

       [[315, 341]],

       [[315, 342]],

       [[316, 343]],

       [[316, 344]],

       [[317, 345]],

       [[317, 355]],

       [[316, 356]],

       [[316, 358]],

       [[314, 360]],

       [[314, 361]],

       [[311, 364]],

       [[310, 364]],

       [[308, 366]],

       [[306, 366]],

       [[305, 367]],

       [[295, 367]],

       [[294, 366]],

       [[293, 366]],

       [[292, 365]],

       [[291, 365]],

       [[290, 364]],

       [[289, 364]],

       [[286, 361]],

       [[286, 360]],

       [[284, 358]],

       [[284, 357]],

       [[283, 356]],

       [[283, 354]],

       [[282, 353]],

       [[282, 347]],

       [[283, 346]],

       [[283, 344]],

       [[285, 342]],

       [[285, 341]],

       [[

In [120]:
import cv2
from cv2.typing import MatLike
import numpy as np

img = np.zeros((500,500,3),np.uint8)
cv2.rectangle( img,
              (50,50),
              (150,150),
              (0,0,255),
              3
    
)

cv2.circle(
    img,
    (200,400),
    39,
    (255,0,0),
    3
)

cv2.polylines(
    img,
    [np.asarray([(175,175),(200,350),(150,350)])],
    True,
    (0,255,0),
    3
)

# Converting image to gray scale
gray= cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# APPLYING gaussian blur
blur = cv2.GaussianBlur(img,(5,5),0)
# Convert to binary image
ret,thresh = cv2.threshold(blur,127,255,cv2.THRESH_BINARY_INV)
# Canny 
edges = cv2.Canny(
    thresh,
    100,230
)

contours,hierarchy = cv2.findContours(
    edges,
    cv2.RETR_LIST,
    cv2.CHAIN_APPROX_SIMPLE,
    offset = (2,2)
)

for contour in contours:
    print(contour)
    epsilon = 0.02*cv2.arcLength(contour,True)
    print(epsilon)
    approx = cv2.approxPolyDP(contour,epsilon,True)

    corners=len(approx)
    if corners==3:
        shape_name="Triangle"
        cv2.drawContours(img,[approx],0,(200,100,100),1)
        cv2.putText(img,shape_name,tuple(approx[0][0]),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,255,245))
    elif corners==4:
        shape_name="Rectangle"
        cv2.drawContours(img,[approx],0,(200,100,100),1)
        cv2.putText(img,shape_name,tuple(approx[0][0]),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,255,245))
    elif corners>5:
        shape_name="Circle"
        cv2.drawContours(img,[approx],0,(200,100,100),1)
        cv2.putText(img,shape_name,tuple(approx[0][0]),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,255,245))
        
    else:
        shape_name="Unkown"

    
    
    # print(shape_name,"\n",approx,"\n")
    
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[197 366]]

 [[198 365]]

 [[206 365]]

 [[207 366]]

 [[210 366]]

 [[211 367]]

 [[214 367]]

 [[215 368]]

 [[216 368]]

 [[217 369]]

 [[218 369]]

 [[220 371]]

 [[221 371]]

 [[222 372]]

 [[223 372]]

 [[232 381]]

 [[232 382]]

 [[233 383]]

 [[233 384]]

 [[235 386]]

 [[235 387]]

 [[236 388]]

 [[236 390]]

 [[237 391]]

 [[237 395]]

 [[238 396]]

 [[238 408]]

 [[237 409]]

 [[237 412]]

 [[236 413]]

 [[236 416]]

 [[235 417]]

 [[235 418]]

 [[233 420]]

 [[233 421]]

 [[232 422]]

 [[232 423]]

 [[223 432]]

 [[222 432]]

 [[221 433]]

 [[220 433]]

 [[218 435]]

 [[217 435]]

 [[216 436]]

 [[213 436]]

 [[212 437]]

 [[209 437]]

 [[208 438]]

 [[196 438]]

 [[195 437]]

 [[191 437]]

 [[190 436]]

 [[188 436]]

 [[187 435]]

 [[186 435]]

 [[185 434]]

 [[184 434]]

 [[182 432]]

 [[181 432]]

 [[172 423]]

 [[172 422]]

 [[171 421]]

 [[171 420]]

 [[169 418]]

 [[169 417]]

 [[168 416]]

 [[168 415]]

 [[167 414]]

 [[167 411]]

 [[166 410]]

 [[166 407]]

 [[165

`Drawing Contours on live video`

In [125]:
import cv2
from cv2.typing import MatLike
import numpy as np

cap = cv2.VideoCapture(0)
while True:
    ret,frame =cap.read()
    if not ret: break
    # Converting image to gray scale
    gray= cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    # APPLYING gaussian blur
    blur = cv2.GaussianBlur(frame,(5,5),0)
    # Convert to binary image
    ret,thresh = cv2.threshold(blur,127,255,cv2.THRESH_BINARY_INV)
    # Canny 
    edges = cv2.Canny(
        thresh,
        100,230
    )

    contours,hierarchy = cv2.findContours(
        edges,
        cv2.RETR_LIST,
        cv2.CHAIN_APPROX_SIMPLE,
        offset = (2,2)
    )

    for contour in contours:
        # print(contour)
        epsilon = 0.02*cv2.arcLength(contour,True)
        # print(epsilon)
        approx = cv2.approxPolyDP(contour,epsilon,True)

        corners=len(approx)
        if corners==3:
            shape_name="Triangle"
            cv2.drawContours(frame,[approx],0,(200,100,100),3)
            # cv2.putText(frame,shape_name,tuple(approx[0][0]),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,255,245))
        elif corners==4:
            shape_name="Rectangle"
            cv2.drawContours(frame,[approx],0,(200,100,100),3)
            # cv2.putText(frame,shape_name,tuple(approx[0][0]),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,255,245))
        elif corners>5:
            shape_name="Circle"
            cv2.drawContours(frame,[approx],0,(200,100,100),3)
            # cv2.putText(frame,shape_name,tuple(approx[0][0]),cv2.FONT_HERSHEY_COMPLEX,0.7,(255,255,245))
            
        else:
            shape_name="Unkown"

    cv2.imshow("image",frame)
    if cv2.waitKey(1)==ord('q'):break

cap.release()
cv2.destroyAllWindows()

# `Template Matching`

Template matching is a technique used in computer vision to find a template (a
small image) within a larger image. OpenCV provides functions that can be used
to perform template matching in images.

The basic idea behind template matching is to slide a template image over a
larger image and compare the pixel values in the template image with the
corresponding pixels in the larger image. This comparison can be performed using two methods `Sum of Squared Differences (SSD)` correlation coefficient or `Normalized Cross-correlation (NCC)`.

-  cv2.matchTemplate()

    Parameters -> input_img and template_img
    Returns -> a response image that shows the similarity between the template and the input image.
    - Several mtds for matching the templates
      1. Sum of squared Difference `(cv2.TM_SQDIFF)`-> calculates the sum of squared differences between the template and the
input image at each pixel location. The **minimum value in the  resulting response image corresponds to the location of the best match.**
      2. Normalized Sum of Squarred differnces `(cv2.TM_SQDIFF_NORMED)`-> similar to the sum of squared differences method, but the resulting response image is **normalized to have values between 0 and 1**. The minimum value in the normalized response image corresponds to the location of the best match.

      3.  Cross-correlation `(cv2.TM_CCORR)`: This method calculates the **crosscorrelation between the template and the input image at each pixel location**. The **maximum value in the resulting response image corresponds** to the location of the best match.
      
      4. Normalized cross-correlation `(cv2.TM_CCORR_NORMED)`: This method is similar to the **cross-correlation method, but the resulting response image is normalized to have values between 0 and 1**. The **maximum value in the normalized response image corresponds to the location of the best match**.
      5. Correlation coefficient `(cv2.TM_CCOEFF)`: This method calculates the **correlation coefficient** between the template and the input image at each pixel location. The **maximum value in the resulting response image corresponds to the location of the best match**.
      
      6. Normalized correlation coefficient `(cv2.TM_CCOEFF_NORMED)`: This method is similar to the correlation coefficient method, but the resulting response image is **normalized to have values between -1 and 1**. The **maximum value in the normalized response image corresponds to the location of the best match**.

In [133]:
# For image
import cv2
import numpy as np

small = cv2.resize(
    cv2.imread('small.jpg'),
    (300, 300)
)
img = cv2.imread('large.jpg')
tem_h, tem_w, _ = small.shape

result = cv2.matchTemplate(
    img,
    small,
    cv2.TM_CCORR_NORMED
)

# Find the BEST match
min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)

threshold_val = 0.8

if max_val >= threshold_val:

    top_left = max_loc

    bottom_right = (
        top_left[0] + tem_w,
        top_left[1] + tem_h
    )

    cv2.rectangle(
        img,
        top_left,
        bottom_right,
        (0, 0, 255),
        2
    )

    cv2.putText(
        img,
        f"Match: {max_val:.2f}",
        (top_left[0], top_left[1] - 10),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.7,
        (0, 0, 255),
        2
    )

cv2.imshow('Live', img)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
import cv2
import numpy as np

small = cv2.resize(
    cv2.imread('small.jpg'),
    (300, 300)
)

tem_h, tem_w, _ = small.shape

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()

    if not ret:
        break

    result = cv2.matchTemplate(
        frame,
        small,
        cv2.TM_CCORR_NORMED
    )

    # Find the BEST match
    min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)

    threshold_val = 0.8

    if max_val >= threshold_val:

        top_left = max_loc

        bottom_right = (
            top_left[0] + tem_w,
            top_left[1] + tem_h
        )

        cv2.rectangle(
            frame,
            top_left,
            bottom_right,
            (0, 0, 255),
            2
        )

        cv2.putText(
            frame,
            f"Match: {max_val:.2f}",
            (top_left[0], top_left[1] - 10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (0, 0, 255),
            2
        )

    cv2.imshow('Live', frame)

    if cv2.waitKey(1) == 27: #press esc to exit
        break

cap.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
from typing import Tuple


def portrait_blur_pipeline(
    image: np.ndarray,
    face_box: Tuple[int, int, int, int],
    blur_ksize: int = 45
) -> np.ndarray:
    """
    Applies photographic portrait bokeh background blur around a detected face.
    face_box: (x, y, w, h)
    """
    x, y, w, h = face_box
    img_h, img_w = image.shape[:2]

    # 1. Apply heavy background blur across the entire frame
    ksize = blur_ksize if blur_ksize % 2 == 1 else blur_ksize + 1
    blurred_background = cv2.GaussianBlur(
        image, (ksize, ksize), 0
    )

    # 2. Construct feathered elliptical mask centered on face
    mask = np.zeros((img_h, img_w), dtype=np.float32)

    center = (
        int(x + w / 2),
        int(y + h / 2)
    )

    axes = (
        int(w * 0.75),
        int(h * 0.95)
    )

    cv2.ellipse(
        mask,
        center,
        axes,
        angle=0,
        startAngle=0,
        endAngle=360,
        color=1.0,
        thickness=-1
    )

    # Feather mask
    mask_feathered = cv2.GaussianBlur(
        mask,
        (51, 51),
        0
    )

    alpha = np.expand_dims(
        mask_feathered,
        axis=2
    )

    # 3. Alpha compositing
    composite = (
        image.astype(np.float32) * alpha
        +
        blurred_background.astype(np.float32) * (1.0 - alpha)
    )

    return np.clip(
        composite,
        0,
        255
    ).astype(np.uint8)


def run_live_portrait_blur():
    """
    Captures webcam video, detects a face, and applies
    portrait background blur in real time.
    """

    # Load OpenCV's Haar Cascade face detector
    face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades +
    "haarcascade_frontalface_default.xml"
)


    if face_cascade.empty():
        raise RuntimeError("Could not load Haar Cascade face detector.")

    # Open default webcam
    cap = cv2.VideoCapture(0)

    if not cap.isOpened():
        raise RuntimeError("Could not open webcam.")

    print("Live portrait blur started.")
    print("Press 'q' to quit.")

    while True:
        # --------------------------------------------------
        # 1. Capture frame
        # --------------------------------------------------
        ret, frame = cap.read()

        if not ret:
            print("Failed to read frame from webcam.")
            break

        # --------------------------------------------------
        # 2. Mirror the webcam
        # --------------------------------------------------
        frame = cv2.flip(frame, 1)

        # --------------------------------------------------
        # 3. Convert frame to grayscale for face detection
        # --------------------------------------------------
        gray = cv2.cvtColor(
            frame,
            cv2.COLOR_BGR2GRAY
        )

        # --------------------------------------------------
        # 4. Detect faces
        # --------------------------------------------------
        faces = face_cascade.detectMultiScale(
            gray,
            scaleFactor=1.1,
            minNeighbors=5,
            minSize=(80, 80)
        )

        # --------------------------------------------------
        # 5. Apply portrait blur
        # --------------------------------------------------
        output = frame

        if len(faces) > 0:

            # Use the largest detected face
            face_box = max(
                faces,
                key=lambda box: box[2] * box[3]
            )

            # Call your pipeline
            output = portrait_blur_pipeline(
                frame,
                tuple(face_box),
                blur_ksize=45
            )

            # Optional: draw face detection rectangle
            x, y, w, h = face_box

            cv2.rectangle(
                output,
                (x, y),
                (x + w, y + h),
                (0, 255, 0),
                2
            )

        # --------------------------------------------------
        # 6. Display result
        # --------------------------------------------------
        cv2.imshow(
            "Live Portrait Blur",
            output
        )

        # --------------------------------------------------
        # 7. Exit when Q is pressed
        # --------------------------------------------------
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    # ------------------------------------------------------
    # 8. Cleanup
    # ------------------------------------------------------
    cap.release()
    cv2.destroyAllWindows()


run_live_portrait_blur()


RuntimeError: Could not load Haar Cascade face detector.

In [1]:
%pip uninstall opencv-python opencv-python-headless opencv-contrib-python -y
%pip install opencv-contrib-python==5.0.0.93


Found existing installation: opencv-contrib-python 5.0.0.93
Uninstalling opencv-contrib-python-5.0.0.93:
  Successfully uninstalled opencv-contrib-python-5.0.0.93
Note: you may need to restart the kernel to use updated packages.


  Using cached opencv_contrib_python-5.0.0.93-cp37-abi3-win_amd64.whl.metadata (20 kB)
Using cached opencv_contrib_python-5.0.0.93-cp37-abi3-win_amd64.whl (53.8 MB)
Note: you may need to restart the kernel to use updated packages.


In [1]:
import cv2

print("OpenCV version:", getattr(cv2, "__version__", "unknown"))
print("cv2 location:", getattr(cv2, "__file__", "unknown"))
print("Has CascadeClassifier:", hasattr(cv2, "CascadeClassifier"))


OpenCV version: 5.0.0
cv2 location: c:\Users\Hemang.bodana\Downloads\Intern\Module-6\.venv\Lib\site-packages\cv2\__init__.py
Has CascadeClassifier: True
